#! /bin/bash

cd `dirname $0`

arch="`arch`"
tag=
uid=
platform=
args=()

# Except on Darwin, adopt current UID by default.
if test "`uname`" != Darwin; then
    uid="`id -u`"
    if [ $uid -le 1000 ]; then uid=""; fi
fi

usage () {
    echo "Usage: ./build-docker" 1>&2
    exit 1
}

while test "$#" -ne 0; do
    if expr "$1" : "--progress=.*" "|" "$1" = "--no-cache" > /dev/null; then
        args+=( "$1" )
        shift
    elif test "$1" = "-u" -o "$1" = "--user"; then
        if expr "$2" : "[0-9][0-9]*$" >/dev/null; then
            uid="$2"
            shift 2
        else
            usage
        fi
    elif expr "$1" : "-u[0-9]*$" "|" "$1" : "--user=[0-9][0-9]*" >/dev/null; then
        uid="`echo "$1" | sed 's/^[^0-9]*//'`"
        shift
    elif test "$1" = "-t" -o "$1" = "--tag"; then
        if expr "$2" : "..*$" >/dev/null; then
            tag="$2"
            shift 2
        else
            usage
        fi
    elif expr "$1" : "-t..*$" "|" "$1" : "--tag=..*" >/dev/null; then
        tag="`echo "$1" | sed 's/^--tag=//;s/^-t//'`"
        shift
    else
        usage
    fi
done

if test -z "$tag"; then
    tag=cs2620:latest
fi

if test -n "$uid"; then
    args+=( --build-arg UID="$uid" )
fi

exec docker build -t "$tag" -f Dockerfile ${args[@]} .
